services:
  postgres:
    image: postgres:15
    container_name: osint-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 753951456
      POSTGRES_DB: nexus-security-gr
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - nexus-net

  n8n:
    image: n8nio/n8n:latest
    container_name: osint-n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=753951456
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=America/Argentina/Buenos_Aires
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=nexus-security-gr
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=753951456
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - nexus-net

  sentiment-api:
    build: ./sentiment-api
    container_name: osint-sentiment-api
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - nexus-net

volumes:
  postgres_data:
  n8n_data:

networks:
  nexus-net:
    driver: bridge
