services:
  postgres:
    image: postgres:15
    container_name: osint-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 753951456
      POSTGRES_DB: nexus-security-gr
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
  n8n:
    image: n8nio/n8n:latest
    container_name: osint-n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=753951456
      - N8N_HOST=localhost # Cambiar a tu dominio si lo despliegas públicamente
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/ # Cambiar a tu URL de webhook si usas dominios
      - GENERIC_TIMEZONE=America/Argentina/Buenos_Aires # Ajusta a tu zona horaria
      # Para utilizar PostgreSQL como base de datos (recomendado para producción)
      # Descomentar y configurar si se desea usar la base de datos PostgreSQL ya instalada
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=localhost # O la IP/nombre del host de tu servidor PostgreSQL
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=nexus-security-gr # Nombre de la base de datos para n8n
      - DB_POSTGRESDB_USER=postgres # Usuario de PostgreSQL para n8n
      - DB_POSTGRESDB_PASSWORD=753951456
    volumes:
      - n8n_data:/home/hjcxd/Onedrive/UTN/Tesis/NSG/Proyecto/nexus-security-group/datos.n8n
    depends_on:
      - postgres
    restart: unless-stopped

  sentiment-api:
    build: ./sentiment-api
    container_name: osint-sentiment-api
    ports:
      - "5000:5000"
    restart: unless-stopped
volumes:
  n8n_data: #Define un volumen nombrado para la persistencia de los datos internos de n8n (workflows, credenciales, etc.).
  postgres_data:
EOF
